"""
Pydantic Schemas

All request/response schemas for API endpoints.
"""
from backend.schemas.auth import (
    UserRegister,
    UserLogin,
    TokenResponse,
    TokenRefresh,
    UserResponse,
    UserUpdate,
    PasswordChange,
    PasswordResetRequest,
    PasswordReset,
    EmailVerificationRequest,
    EmailVerificationResend,
    AuthStatus,
)
from backend.schemas.agent_message import (
    AgentMessageBase,
    AgentMessageCreate,
    AgentMessageResponse,
    MessageStats,
    TaskAssignment,
    StatusRequest,
    StatusUpdate,
    Question,
    Answer,
    HumanInterventionRequired,
    CodeReviewRequest,
    CodeReviewResponse,
    TaskCompletion,
    Standup,
    MessagePayload,
)
from backend.schemas.squad import (
    SquadBase,
    SquadCreate,
    SquadUpdate,
    SquadResponse,
    SquadMemberSummary,
    SquadWithAgents,
    SquadCostEstimate,
)
from backend.schemas.squad_member import (
    SquadMemberBase,
    SquadMemberCreate,
    SquadMemberUpdate,
    SquadMemberResponse,
    SquadMemberWithConfig,
    SquadComposition,
)
from backend.schemas.task_execution import (
    TaskExecutionBase,
    TaskExecutionCreate,
    TaskExecutionResponse,
    TaskExecutionWithMessages,
    TaskExecutionSummary,
    TaskExecutionCancel,
    HumanIntervention,
)
from backend.schemas.conversation import (
    ConversationStateEnum,
    ConversationBase,
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationWithDetails,
    ConversationEventBase,
    ConversationEventCreate,
    ConversationEventResponse,
    InitiateQuestionRequest,
    InitiateQuestionResponse,
    SendAcknowledgmentRequest,
    SendAnswerRequest,
    EscalateConversationRequest,
    CantHelpRequest,
    ConversationStatsResponse,
    ConversationTimeline,
)
from backend.schemas.routing_rule import (
    RoutingRuleBase,
    RoutingRuleCreate,
    RoutingRuleUpdate,
    RoutingRuleResponse,
    RoutingRuleWithDetails,
    RoutingRuleDefinition,
    DefaultRoutingTemplateBase,
    DefaultRoutingTemplateCreate,
    DefaultRoutingTemplateUpdate,
    DefaultRoutingTemplateResponse,
    ApplyTemplateRequest,
    ApplyTemplateResponse,
    RoutingChainRequest,
    RoutingChainResponse,
    BulkCreateRoutingRulesRequest,
    BulkCreateRoutingRulesResponse,
    RoutingRuleStats,
    ValidateRoutingConfigRequest,
    ValidateRoutingConfigResponse,
)
from backend.schemas.template import (
    TemplateListResponse,
    TemplateDetailResponse,
    AgentDefinition,
    RoutingRuleDefinition as TemplateRoutingRuleDefinition,
    SuccessMetric,
    ExampleConversation,
    TemplateDefinition,
    ApplyTemplateRequest as TemplateApplyRequest,
    ApplyTemplateResponse as TemplateApplyResponse,
    CreateTemplateRequest,
    UpdateTemplateRequest,
    CreatedAgent,
    CreatedRoutingRule,
)
from backend.schemas.multi_turn_conversation import (
    ConversationType,
    ParticipantType,
    ConversationStatus,
    MessageRole,
    ParticipantRole,
    CreateUserAgentConversationRequest,
    CreateAgentAgentConversationRequest,
    ConversationResponse as MultiTurnConversationResponse,
    ConversationWithMessagesResponse,
    ConversationListResponse,
    SendMessageRequest,
    MessageResponse,
    MessageListResponse,
    ConversationHistoryResponse,
    AddParticipantRequest,
    ParticipantResponse,
    ParticipantListResponse,
    UpdateConversationTitleRequest,
    UpdateConversationSummaryRequest,
    UpdateConversationTagsRequest,
    UserConversationStatsResponse,
    AgentConversationStatsResponse,
)
from backend.schemas.workflow import (
    TaskSpawnRequest,
    TaskSpawnResponse,
    TaskResponse,
    TaskStatusUpdate,
    TaskListResponse,
)
from backend.schemas.branching import (
    CreateBranchRequest,
    BranchResponse,
    MergeBranchRequest,
    BranchTasksResponse,
)
from backend.schemas.intelligence import (
    TaskSuggestionResponse,
    WorkflowPredictionResponse,
    OptimizedTaskOrderResponse,
)
from backend.schemas.ml import (
    OptimizationOpportunityResponse,
    TaskValuePredictionResponse,
    ModelMetricsResponse,
    TrainModelRequest,
)
from backend.schemas.mcp import (
    MCPSessionInfo,
    MCPToolResponse,
    MCPToolsListResponse,
)

__all__ = [
    # Auth schemas
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "TokenRefresh",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    "EmailVerificationRequest",
    "EmailVerificationResend",
    "AuthStatus",
    # Agent message schemas
    "AgentMessageBase",
    "AgentMessageCreate",
    "AgentMessageResponse",
    "MessageStats",
    "TaskAssignment",
    "StatusRequest",
    "StatusUpdate",
    "Question",
    "Answer",
    "HumanInterventionRequired",
    "CodeReviewRequest",
    "CodeReviewResponse",
    "TaskCompletion",
    "Standup",
    "MessagePayload",
    # Squad schemas
    "SquadBase",
    "SquadCreate",
    "SquadUpdate",
    "SquadResponse",
    "SquadMemberSummary",
    "SquadWithAgents",
    "SquadCostEstimate",
    # Squad member schemas
    "SquadMemberBase",
    "SquadMemberCreate",
    "SquadMemberUpdate",
    "SquadMemberResponse",
    "SquadMemberWithConfig",
    "SquadComposition",
    # Task execution schemas
    "TaskExecutionBase",
    "TaskExecutionCreate",
    "TaskExecutionResponse",
    "TaskExecutionWithMessages",
    "TaskExecutionSummary",
    "TaskExecutionCancel",
    "HumanIntervention",
    # Conversation schemas
    "ConversationStateEnum",
    "ConversationBase",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationWithDetails",
    "ConversationEventBase",
    "ConversationEventCreate",
    "ConversationEventResponse",
    "InitiateQuestionRequest",
    "InitiateQuestionResponse",
    "SendAcknowledgmentRequest",
    "SendAnswerRequest",
    "EscalateConversationRequest",
    "CantHelpRequest",
    "ConversationStatsResponse",
    "ConversationTimeline",
    # Routing rule schemas
    "RoutingRuleBase",
    "RoutingRuleCreate",
    "RoutingRuleUpdate",
    "RoutingRuleResponse",
    "RoutingRuleWithDetails",
    "RoutingRuleDefinition",
    "DefaultRoutingTemplateBase",
    "DefaultRoutingTemplateCreate",
    "DefaultRoutingTemplateUpdate",
    "DefaultRoutingTemplateResponse",
    "ApplyTemplateRequest",
    "ApplyTemplateResponse",
    "RoutingChainRequest",
    "RoutingChainResponse",
    "BulkCreateRoutingRulesRequest",
    "BulkCreateRoutingRulesResponse",
    "RoutingRuleStats",
    "ValidateRoutingConfigRequest",
    "ValidateRoutingConfigResponse",
    # Template schemas
    "TemplateListResponse",
    "TemplateDetailResponse",
    "AgentDefinition",
    "TemplateRoutingRuleDefinition",
    "SuccessMetric",
    "ExampleConversation",
    "TemplateDefinition",
    "TemplateApplyRequest",
    "TemplateApplyResponse",
    "CreateTemplateRequest",
    "UpdateTemplateRequest",
    "CreatedAgent",
    "CreatedRoutingRule",
    # Multi-turn conversation schemas
    "ConversationType",
    "ParticipantType",
    "ConversationStatus",
    "MessageRole",
    "ParticipantRole",
    "CreateUserAgentConversationRequest",
    "CreateAgentAgentConversationRequest",
    "MultiTurnConversationResponse",
    "ConversationWithMessagesResponse",
    "ConversationListResponse",
    "SendMessageRequest",
    "MessageResponse",
    "MessageListResponse",
    "ConversationHistoryResponse",
    "AddParticipantRequest",
    "ParticipantResponse",
    "ParticipantListResponse",
    "UpdateConversationTitleRequest",
    "UpdateConversationSummaryRequest",
    "UpdateConversationTagsRequest",
    "UserConversationStatsResponse",
    "AgentConversationStatsResponse",
    # Workflow schemas
    "TaskSpawnRequest",
    "TaskSpawnResponse",
    "TaskResponse",
    "TaskStatusUpdate",
    "TaskListResponse",
    "CreateBranchRequest",
    "BranchResponse",
    "MergeBranchRequest",
    "BranchTasksResponse",
    "TaskSuggestionResponse",
    "WorkflowPredictionResponse",
    "OptimizedTaskOrderResponse",
    "OptimizationOpportunityResponse",
    "TaskValuePredictionResponse",
    "ModelMetricsResponse",
    "TrainModelRequest",
    "MCPSessionInfo",
    "MCPToolResponse",
    "MCPToolsListResponse",
]
