"""
Pydantic Schemas

All request/response schemas for API endpoints.
"""
from backend.schemas.auth import (
    UserRegister,
    UserLogin,
    TokenResponse,
    TokenRefresh,
    UserResponse,
    UserUpdate,
    PasswordChange,
    PasswordResetRequest,
    PasswordReset,
    EmailVerificationRequest,
    EmailVerificationResend,
    AuthStatus,
)
from backend.schemas.agent_message import (
    AgentMessageBase,
    AgentMessageCreate,
    AgentMessageResponse,
    MessageStats,
    TaskAssignment,
    StatusRequest,
    StatusUpdate,
    Question,
    Answer,
    HumanInterventionRequired,
    CodeReviewRequest,
    CodeReviewResponse,
    TaskCompletion,
    Standup,
    MessagePayload,
)
from backend.schemas.squad import (
    SquadBase,
    SquadCreate,
    SquadUpdate,
    SquadResponse,
    SquadMemberSummary,
    SquadWithAgents,
    SquadCostEstimate,
)
from backend.schemas.squad_member import (
    SquadMemberBase,
    SquadMemberCreate,
    SquadMemberUpdate,
    SquadMemberResponse,
    SquadMemberWithConfig,
    SquadComposition,
)
from backend.schemas.task_execution import (
    TaskExecutionBase,
    TaskExecutionCreate,
    TaskExecutionResponse,
    TaskExecutionWithMessages,
    TaskExecutionSummary,
    TaskExecutionCancel,
    HumanIntervention,
)
from backend.schemas.conversation import (
    ConversationStateEnum,
    ConversationBase,
    ConversationCreate,
    ConversationUpdate,
    ConversationResponse,
    ConversationWithDetails,
    ConversationEventBase,
    ConversationEventCreate,
    ConversationEventResponse,
    InitiateQuestionRequest,
    InitiateQuestionResponse,
    SendAcknowledgmentRequest,
    SendAnswerRequest,
    EscalateConversationRequest,
    CantHelpRequest,
    ConversationStatsResponse,
    ConversationTimeline,
)
from backend.schemas.routing_rule import (
    RoutingRuleBase,
    RoutingRuleCreate,
    RoutingRuleUpdate,
    RoutingRuleResponse,
    RoutingRuleWithDetails,
    RoutingRuleDefinition,
    DefaultRoutingTemplateBase,
    DefaultRoutingTemplateCreate,
    DefaultRoutingTemplateUpdate,
    DefaultRoutingTemplateResponse,
    ApplyTemplateRequest,
    ApplyTemplateResponse,
    RoutingChainRequest,
    RoutingChainResponse,
    BulkCreateRoutingRulesRequest,
    BulkCreateRoutingRulesResponse,
    RoutingRuleStats,
    ValidateRoutingConfigRequest,
    ValidateRoutingConfigResponse,
)

__all__ = [
    # Auth schemas
    "UserRegister",
    "UserLogin",
    "TokenResponse",
    "TokenRefresh",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    "EmailVerificationRequest",
    "EmailVerificationResend",
    "AuthStatus",
    # Agent message schemas
    "AgentMessageBase",
    "AgentMessageCreate",
    "AgentMessageResponse",
    "MessageStats",
    "TaskAssignment",
    "StatusRequest",
    "StatusUpdate",
    "Question",
    "Answer",
    "HumanInterventionRequired",
    "CodeReviewRequest",
    "CodeReviewResponse",
    "TaskCompletion",
    "Standup",
    "MessagePayload",
    # Squad schemas
    "SquadBase",
    "SquadCreate",
    "SquadUpdate",
    "SquadResponse",
    "SquadMemberSummary",
    "SquadWithAgents",
    "SquadCostEstimate",
    # Squad member schemas
    "SquadMemberBase",
    "SquadMemberCreate",
    "SquadMemberUpdate",
    "SquadMemberResponse",
    "SquadMemberWithConfig",
    "SquadComposition",
    # Task execution schemas
    "TaskExecutionBase",
    "TaskExecutionCreate",
    "TaskExecutionResponse",
    "TaskExecutionWithMessages",
    "TaskExecutionSummary",
    "TaskExecutionCancel",
    "HumanIntervention",
    # Conversation schemas
    "ConversationStateEnum",
    "ConversationBase",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationWithDetails",
    "ConversationEventBase",
    "ConversationEventCreate",
    "ConversationEventResponse",
    "InitiateQuestionRequest",
    "InitiateQuestionResponse",
    "SendAcknowledgmentRequest",
    "SendAnswerRequest",
    "EscalateConversationRequest",
    "CantHelpRequest",
    "ConversationStatsResponse",
    "ConversationTimeline",
    # Routing rule schemas
    "RoutingRuleBase",
    "RoutingRuleCreate",
    "RoutingRuleUpdate",
    "RoutingRuleResponse",
    "RoutingRuleWithDetails",
    "RoutingRuleDefinition",
    "DefaultRoutingTemplateBase",
    "DefaultRoutingTemplateCreate",
    "DefaultRoutingTemplateUpdate",
    "DefaultRoutingTemplateResponse",
    "ApplyTemplateRequest",
    "ApplyTemplateResponse",
    "RoutingChainRequest",
    "RoutingChainResponse",
    "BulkCreateRoutingRulesRequest",
    "BulkCreateRoutingRulesResponse",
    "RoutingRuleStats",
    "ValidateRoutingConfigRequest",
    "ValidateRoutingConfigResponse",
]
